name: Cross-OS Tests

on: [push, pull_request]

env:
  GITHUB_TOKEN: 1
  GITLAB_TOKEN: 1

jobs:
  test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        node:
          - 10
          - 12
          - 14
          - 16

    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} (Node v${{ matrix.node }})

    steps:
      - uses: actions/checkout@v2
      - run: git config --global user.name User
      - run: git config --global user.email user@example.org
      - run: npm install
      - run: npm test
